# --- RelaxedQMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: "relaxed_qmix"  # Changed from "qmix" to "relaxed_qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

# RelaxedQMIX specific parameters
correction_epsilon: 0.1  # Scale factor for correction term
reg_lambda: 0.01  # Weight for regularization loss

name: "relaxed_qmix"  